
# MED01: ¿Qué estaciones hay?

PREFIX edintmed: <https://edint.es/def/medio-ambiente#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?platform ?label
WHERE {
  ?platform a edintmed:SensorPlatform ;
            rdfs:label ?label .
}


