
# MED04  ¿Quién ha fabricado cada sensor?

PREFIX schema: <http://schema.org/>
PREFIX edintmed: <https://edint.es/def/medio-ambiente#>

SELECT ?manufacturer ?manufacturerLabel ?sensor 
WHERE {
  ?sensor a edintmed:EnvironmentalSensor ;
          schema:manufacturer ?manufacturer .
  OPTIONAL { ?manufacturer rdfs:label ?manufacturerLabel }
}
ORDER BY ?manufacturer


# Variante: Para un sensor concreto

PREFIX schema: <http://schema.org/>
PREFIX edintmed: <https://edint.es/def/medio-ambiente#>
PREFIX ex: <http://example.org/>

# Valor por defecto para <URI-del-sensor>:
#   Usa ex:Sensor_Temp_001 (Sensor de temperatura - PT100, en example1.ttl)
#   O bien ex:Sensor_NO2_001, ex:Sensor_Press_001
SELECT ?manufacturer ?manufacturerLabel
WHERE {
  BIND(ex:Sensor_Temp_001 AS ?sensor)
  ?sensor a edintmed:EnvironmentalSensor ;
          schema:manufacturer ?manufacturer .
  OPTIONAL { ?manufacturer rdfs:label ?manufacturerLabel }
}
ORDER BY ?manufacturer